/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tictactoeclient;

import java.io.*;
import java.lang.Thread;
import javax.swing.JOptionPane;
import javax.xml.ws.BindingProvider;
/**
 *
 * @author andre
 */
public class TicTacToeInterface extends javax.swing.JFrame {
    TicTacToe.DWTicTacToeService service;
    TicTacToe.DWTicTacToePort tictactoe;
    /**
     * Creates new form TicTacToeInterface
     */
    public TicTacToeInterface() {
        service = new TicTacToe.DWTicTacToeService();
        tictactoe = service.getDWTicTacToePort();
        ((BindingProvider)tictactoe).getRequestContext().put(BindingProvider.SESSION_MAINTAIN_PROPERTY,true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        GoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        GoBack.setText("Go back");
        GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tictactoe.tick(0, 1, 1);
        jButton2.setText("X");
        jButton2.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tictactoe.tick(0, 0, 1);
        //System.out.println(tictactoe.getBoardStr());
        jButton1.setText("X");
        jButton1.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }            
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackActionPerformed
        new MenuGame().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_GoBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tictactoe.tick(0, 2, 1);
        jButton3.setText("X");
        jButton3.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }            
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tictactoe.tick(1, 0, 1);
        jButton4.setText("X");
        jButton4.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }          
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tictactoe.tick(1, 1, 1);
        jButton5.setText("X");
        jButton5.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }           
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        tictactoe.tick(1, 2, 1);
        jButton6.setText("X");
        jButton6.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }           
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        tictactoe.tick(2, 0, 1);
        jButton7.setText("X");
        jButton7.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }            
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        tictactoe.tick(2, 1, 1);
        jButton8.setText("X");
        jButton8.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }           
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        tictactoe.tick(2, 2, 1);
        jButton9.setText("X");
        jButton9.setEnabled(false);
        if (tictactoe.checkWin(1)) {
            String name = JOptionPane.showInputDialog("You've won! \nPlease enter your name:");
            if (name == null) {
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                tictactoe.addToRanking(name);
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                 
            }
        }else{
            if (tictactoe.isFull(1)) {
                JOptionPane.showMessageDialog(this, "It's a tie");
                new MenuGame().setVisible(true);
                this.setVisible(false);
                this.dispose();                
            }else{
                String checkComputer = tictactoe.playComputerRand(2);
                switch (checkComputer) {
                     case "00":
                        jButton1.setText("O");
                        jButton1.setEnabled(false);
                        break;
                     case "01":
                        jButton2.setText("O");
                        jButton2.setEnabled(false);
                        break;
                     case "02":
                        jButton3.setText("O");
                        jButton3.setEnabled(false);
                        break;
                     case "10":
                        jButton4.setText("O");
                        jButton4.setEnabled(false);
                        break;
                     case "11":
                        jButton5.setText("O");
                        jButton5.setEnabled(false);
                        break;
                     case "12":
                        jButton6.setText("O");
                        jButton6.setEnabled(false);
                        break;
                     case "20":
                        jButton7.setText("O");
                        jButton7.setEnabled(false);
                        break;
                     case "21":
                        jButton8.setText("O");
                        jButton8.setEnabled(false);
                        break;
                     case "22":
                        jButton9.setText("O");
                        jButton9.setEnabled(false);
                        break;
                 }
                //jButton1.setText("O");
                if (tictactoe.checkWin(2)) {
                    JOptionPane.showMessageDialog(this, "You've lost");
                    new MenuGame().setVisible(true);
                    this.setVisible(false);
                    this.dispose();                
                }else{
                    if (tictactoe.isFull(1)) {
                        JOptionPane.showMessageDialog(this, "It's a tie");
                        new MenuGame().setVisible(true);
                        this.setVisible(false);
                        this.dispose();                
                    }                    
                }
            }
        }        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
