//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DW_TicTacToe", ConfigurationName="TicTacToe.DW_TicTacToePort")]
    public interface DW_TicTacToePort
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:DW_TicTacToe#tick")]
        System.Threading.Tasks.Task tickAsync(TicTacToe.tick request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#searchWin", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.searchWinResponse> searchWinAsync(TicTacToe.searchWinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#searchBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.searchBlockResponse> searchBlockAsync(TicTacToe.searchBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#searchTick", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.searchTickResponse> searchTickAsync(TicTacToe.searchTickRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:DW_TicTacToe#playComputer")]
        System.Threading.Tasks.Task playComputerAsync(TicTacToe.playComputer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#getBoardStr", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.getBoardStrResponse> getBoardStrAsync(TicTacToe.getBoardStrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#prueba", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.pruebaResponse> pruebaAsync(TicTacToe.pruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#checkWin", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.checkWinResponse> checkWinAsync(TicTacToe.checkWinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DW_TicTacToe#isFull", ReplyAction="*")]
        System.Threading.Tasks.Task<TicTacToe.isFullResponse> isFullAsync(TicTacToe.isFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:DW_TicTacToe#playComputerRand")]
        System.Threading.Tasks.Task playComputerRandAsync(TicTacToe.playComputerRand request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tick", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class tick
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fila;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int columna;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int jugador;
        
        public tick()
        {
        }
        
        public tick(int fila, int columna, int jugador)
        {
            this.fila = fila;
            this.columna = columna;
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchWinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchWin", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.searchWinRequestBody Body;
        
        public searchWinRequest()
        {
        }
        
        public searchWinRequest(TicTacToe.searchWinRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class searchWinRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jugador;
        
        public searchWinRequestBody()
        {
        }
        
        public searchWinRequestBody(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchWinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchWinResponse", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.searchWinResponseBody Body;
        
        public searchWinResponse()
        {
        }
        
        public searchWinResponse(TicTacToe.searchWinResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class searchWinResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchWinResult;
        
        public searchWinResponseBody()
        {
        }
        
        public searchWinResponseBody(string searchWinResult)
        {
            this.searchWinResult = searchWinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchBlockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchBlock", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.searchBlockRequestBody Body;
        
        public searchBlockRequest()
        {
        }
        
        public searchBlockRequest(TicTacToe.searchBlockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class searchBlockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jugador;
        
        public searchBlockRequestBody()
        {
        }
        
        public searchBlockRequestBody(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchBlockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchBlockResponse", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.searchBlockResponseBody Body;
        
        public searchBlockResponse()
        {
        }
        
        public searchBlockResponse(TicTacToe.searchBlockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class searchBlockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchBlockResult;
        
        public searchBlockResponseBody()
        {
        }
        
        public searchBlockResponseBody(string searchBlockResult)
        {
            this.searchBlockResult = searchBlockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchTickRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchTick", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.searchTickRequestBody Body;
        
        public searchTickRequest()
        {
        }
        
        public searchTickRequest(TicTacToe.searchTickRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class searchTickRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jugador;
        
        public searchTickRequestBody()
        {
        }
        
        public searchTickRequestBody(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchTickResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchTickResponse", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.searchTickResponseBody Body;
        
        public searchTickResponse()
        {
        }
        
        public searchTickResponse(TicTacToe.searchTickResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class searchTickResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTickResult;
        
        public searchTickResponseBody()
        {
        }
        
        public searchTickResponseBody(string searchTickResult)
        {
            this.searchTickResult = searchTickResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="playComputer", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class playComputer
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int jugador;
        
        public playComputer()
        {
        }
        
        public playComputer(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBoardStrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBoardStr", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.getBoardStrRequestBody Body;
        
        public getBoardStrRequest()
        {
        }
        
        public getBoardStrRequest(TicTacToe.getBoardStrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getBoardStrRequestBody
    {
        
        public getBoardStrRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBoardStrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBoardStrResponse", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.getBoardStrResponseBody Body;
        
        public getBoardStrResponse()
        {
        }
        
        public getBoardStrResponse(TicTacToe.getBoardStrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBoardStrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getBoardStrResult;
        
        public getBoardStrResponseBody()
        {
        }
        
        public getBoardStrResponseBody(string getBoardStrResult)
        {
            this.getBoardStrResult = getBoardStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="prueba", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.pruebaRequestBody Body;
        
        public pruebaRequest()
        {
        }
        
        public pruebaRequest(TicTacToe.pruebaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pruebaRequestBody
    {
        
        public pruebaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pruebaResponse", Namespace="urn:DW_TicTacToe", Order=0)]
        public TicTacToe.pruebaResponseBody Body;
        
        public pruebaResponse()
        {
        }
        
        public pruebaResponse(TicTacToe.pruebaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pruebaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pruebaResult;
        
        public pruebaResponseBody()
        {
        }
        
        public pruebaResponseBody(string pruebaResult)
        {
            this.pruebaResult = pruebaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkWin", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class checkWinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int jugador;
        
        public checkWinRequest()
        {
        }
        
        public checkWinRequest(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkWinResponse", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class checkWinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool checkWinResult;
        
        public checkWinResponse()
        {
        }
        
        public checkWinResponse(bool checkWinResult)
        {
            this.checkWinResult = checkWinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isFull", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class isFullRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int jugador;
        
        public isFullRequest()
        {
        }
        
        public isFullRequest(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isFullResponse", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class isFullResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool isFullResult;
        
        public isFullResponse()
        {
        }
        
        public isFullResponse(bool isFullResult)
        {
            this.isFullResult = isFullResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="playComputerRand", WrapperNamespace="urn:DW_TicTacToe", IsWrapped=true)]
    public partial class playComputerRand
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int jugador;
        
        public playComputerRand()
        {
        }
        
        public playComputerRand(int jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DW_TicTacToePortChannel : TicTacToe.DW_TicTacToePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DW_TicTacToePortClient : System.ServiceModel.ClientBase<TicTacToe.DW_TicTacToePort>, TicTacToe.DW_TicTacToePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DW_TicTacToePortClient() : 
                base(DW_TicTacToePortClient.GetDefaultBinding(), DW_TicTacToePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DW_TicTacToePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DW_TicTacToePortClient(EndpointConfiguration endpointConfiguration) : 
                base(DW_TicTacToePortClient.GetBindingForEndpoint(endpointConfiguration), DW_TicTacToePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DW_TicTacToePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DW_TicTacToePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DW_TicTacToePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DW_TicTacToePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DW_TicTacToePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task TicTacToe.DW_TicTacToePort.tickAsync(TicTacToe.tick request)
        {
            return base.Channel.tickAsync(request);
        }
        
        public System.Threading.Tasks.Task tickAsync(int fila, int columna, int jugador)
        {
            TicTacToe.tick inValue = new TicTacToe.tick();
            inValue.fila = fila;
            inValue.columna = columna;
            inValue.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).tickAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.searchWinResponse> TicTacToe.DW_TicTacToePort.searchWinAsync(TicTacToe.searchWinRequest request)
        {
            return base.Channel.searchWinAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.searchWinResponse> searchWinAsync(int jugador)
        {
            TicTacToe.searchWinRequest inValue = new TicTacToe.searchWinRequest();
            inValue.Body = new TicTacToe.searchWinRequestBody();
            inValue.Body.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).searchWinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.searchBlockResponse> TicTacToe.DW_TicTacToePort.searchBlockAsync(TicTacToe.searchBlockRequest request)
        {
            return base.Channel.searchBlockAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.searchBlockResponse> searchBlockAsync(int jugador)
        {
            TicTacToe.searchBlockRequest inValue = new TicTacToe.searchBlockRequest();
            inValue.Body = new TicTacToe.searchBlockRequestBody();
            inValue.Body.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).searchBlockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.searchTickResponse> TicTacToe.DW_TicTacToePort.searchTickAsync(TicTacToe.searchTickRequest request)
        {
            return base.Channel.searchTickAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.searchTickResponse> searchTickAsync(int jugador)
        {
            TicTacToe.searchTickRequest inValue = new TicTacToe.searchTickRequest();
            inValue.Body = new TicTacToe.searchTickRequestBody();
            inValue.Body.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).searchTickAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task TicTacToe.DW_TicTacToePort.playComputerAsync(TicTacToe.playComputer request)
        {
            return base.Channel.playComputerAsync(request);
        }
        
        public System.Threading.Tasks.Task playComputerAsync(int jugador)
        {
            TicTacToe.playComputer inValue = new TicTacToe.playComputer();
            inValue.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).playComputerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.getBoardStrResponse> TicTacToe.DW_TicTacToePort.getBoardStrAsync(TicTacToe.getBoardStrRequest request)
        {
            return base.Channel.getBoardStrAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.getBoardStrResponse> getBoardStrAsync()
        {
            TicTacToe.getBoardStrRequest inValue = new TicTacToe.getBoardStrRequest();
            inValue.Body = new TicTacToe.getBoardStrRequestBody();
            return ((TicTacToe.DW_TicTacToePort)(this)).getBoardStrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.pruebaResponse> TicTacToe.DW_TicTacToePort.pruebaAsync(TicTacToe.pruebaRequest request)
        {
            return base.Channel.pruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.pruebaResponse> pruebaAsync()
        {
            TicTacToe.pruebaRequest inValue = new TicTacToe.pruebaRequest();
            inValue.Body = new TicTacToe.pruebaRequestBody();
            return ((TicTacToe.DW_TicTacToePort)(this)).pruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.checkWinResponse> TicTacToe.DW_TicTacToePort.checkWinAsync(TicTacToe.checkWinRequest request)
        {
            return base.Channel.checkWinAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.checkWinResponse> checkWinAsync(int jugador)
        {
            TicTacToe.checkWinRequest inValue = new TicTacToe.checkWinRequest();
            inValue.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).checkWinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicTacToe.isFullResponse> TicTacToe.DW_TicTacToePort.isFullAsync(TicTacToe.isFullRequest request)
        {
            return base.Channel.isFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicTacToe.isFullResponse> isFullAsync(int jugador)
        {
            TicTacToe.isFullRequest inValue = new TicTacToe.isFullRequest();
            inValue.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).isFullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task TicTacToe.DW_TicTacToePort.playComputerRandAsync(TicTacToe.playComputerRand request)
        {
            return base.Channel.playComputerRandAsync(request);
        }
        
        public System.Threading.Tasks.Task playComputerRandAsync(int jugador)
        {
            TicTacToe.playComputerRand inValue = new TicTacToe.playComputerRand();
            inValue.jugador = jugador;
            return ((TicTacToe.DW_TicTacToePort)(this)).playComputerRandAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DW_TicTacToePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DW_TicTacToePort))
            {
                return new System.ServiceModel.EndpointAddress("https://titanic.ecci.ucr.ac.cr/~ec04740/TicTacToe/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DW_TicTacToePortClient.GetBindingForEndpoint(EndpointConfiguration.DW_TicTacToePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DW_TicTacToePortClient.GetEndpointAddress(EndpointConfiguration.DW_TicTacToePort);
        }
        
        public enum EndpointConfiguration
        {
            
            DW_TicTacToePort,
        }
    }
}
